#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_FILE="$SCRIPT_DIR/vps优化脚本.sh"

grep -Fq 'echo "4. TG-bot通知管理"' "$SCRIPT_FILE"
grep -Fq '4) refresh_screen; tg_notify_menu ;;' "$SCRIPT_FILE"
grep -Fq 'echo "5. 测试脚本合集"' "$SCRIPT_FILE"
grep -Fq '5) refresh_screen; test_scripts_menu ;;' "$SCRIPT_FILE"
! grep -Fq '3) refresh_screen; setup_tg_monitoring ;;' "$SCRIPT_FILE"
grep -Fq 'echo "2. 加入放行端口"' "$SCRIPT_FILE"
grep -Fq '2) refresh_screen; manage_allow_port ;;' "$SCRIPT_FILE"
grep -Fq 'prompt_optional_threshold' "$SCRIPT_FILE"
grep -Fq 'cpu_threshold="$(prompt_optional_threshold "CPU 使用率预警阈值百分比")"' "$SCRIPT_FILE"
grep -Fq 'if (( \$(echo "\$threshold <= 0" | bc -l) )); then' "$SCRIPT_FILE"
grep -Fq 'NETWORK_THRESHOLD_GB > 0' "$SCRIPT_FILE"
grep -Fq 'tg_notify_file()' "$SCRIPT_FILE"
grep -Fq 'printf "%s\n" "$HOME/服务器告警.sh"' "$SCRIPT_FILE"
grep -Fq 'notify_file="$(tg_notify_file)"' "$SCRIPT_FILE"
grep -Fq 'case "\${1:-monitor}" in' "$SCRIPT_FILE"
grep -Fq 'login) send_login_notification ;;' "$SCRIPT_FILE"
grep -Fq 'bash $notify_file login' "$SCRIPT_FILE"
grep -Fq 'CPU 使用情况' "$SCRIPT_FILE"
grep -Fq '内存使用情况' "$SCRIPT_FILE"
grep -Fq '硬盘使用情况' "$SCRIPT_FILE"
grep -Fq '入站流量使用情况' "$SCRIPT_FILE"
grep -Fq '出站流量使用情况' "$SCRIPT_FILE"
grep -Fq 'tg_monitor_status_text' "$SCRIPT_FILE"
grep -Fq 'tg_login_status_text' "$SCRIPT_FILE"
grep -Fq 'echo "已开启"' "$SCRIPT_FILE"
grep -Fq 'echo "已关闭"' "$SCRIPT_FILE"
grep -Fq 'tg_config_value' "$SCRIPT_FILE"
grep -Fq 'existing_token="$(tg_config_value "$notify_file" TELEGRAM_BOT_TOKEN)"' "$SCRIPT_FILE"
grep -Fq 'existing_chat_id="$(tg_config_value "$notify_file" CHAT_ID)"' "$SCRIPT_FILE"
grep -Fq 'existing_server_name="$(tg_config_value "$notify_file" SERVER_DISPLAY_NAME)"' "$SCRIPT_FILE"
grep -Fq 'server_name="$(prompt_required_value "请输入服务器显示名称：")"' "$SCRIPT_FILE"
grep -Fq 'SERVER_DISPLAY_NAME=$(shell_quote "$server_name")' "$SCRIPT_FILE"
grep -Fq 'if [[ -n "\${SERVER_DISPLAY_NAME:-}" ]]; then' "$SCRIPT_FILE"
grep -Fq 'message="ℹ️ \${SERVER_DISPLAY_NAME} 于 \${time} 进行登录' "$SCRIPT_FILE"
grep -Fq '登录地区为：\$location' "$SCRIPT_FILE"
grep -Fq '已检测到现有 Telegram 配置，将直接沿用。' "$SCRIPT_FILE"
grep -Fq 'manage_tg_monitor' "$SCRIPT_FILE"
grep -Fq 'manage_tg_login_notify' "$SCRIPT_FILE"
grep -Fq 'echo "当前状态：$(tg_monitor_status_text)"' "$SCRIPT_FILE"
grep -Fq 'echo "当前状态：$(tg_login_status_text)"' "$SCRIPT_FILE"
grep -Fq 'echo "1. 开启系统资源/流量报警"' "$SCRIPT_FILE"
grep -Fq 'echo "2. 关闭系统资源/流量报警"' "$SCRIPT_FILE"
grep -Fq 'echo "1. 开启 SSH 登录通知"' "$SCRIPT_FILE"
grep -Fq 'echo "2. 关闭 SSH 登录通知"' "$SCRIPT_FILE"
grep -Fq 'echo "1. 系统资源/流量报警"' "$SCRIPT_FILE"
grep -Fq 'echo "2. SSH 登录通知"' "$SCRIPT_FILE"
grep -Fq 'echo "3. Telegram 清除配置信息"' "$SCRIPT_FILE"
! grep -Fq 'echo "1. 系统资源/流量报警：$(tg_monitor_status_text)"' "$SCRIPT_FILE"
! grep -Fq 'echo "2. SSH 登录通知：$(tg_login_status_text)"' "$SCRIPT_FILE"
grep -Fq '1) refresh_screen; manage_tg_monitor ;;' "$SCRIPT_FILE"
grep -Fq '2) refresh_screen; manage_tg_login_notify ;;' "$SCRIPT_FILE"
grep -Fq 'clear_telegram_config' "$SCRIPT_FILE"
grep -Fq '3) refresh_screen; clear_telegram_config; finish_menu_action ;;' "$SCRIPT_FILE"
grep -Fq 'Telegram 配置信息已清除。' "$SCRIPT_FILE"
! grep -Fq '确定清除 Telegram 配置信息吗？' "$SCRIPT_FILE"
grep -Fq 'test_scripts_menu' "$SCRIPT_FILE"
grep -Fq 'echo "测试脚本合集"' "$SCRIPT_FILE"
grep -Fq 'finish_test_script_action' "$SCRIPT_FILE"
grep -Fq 'read -n 1 -s -r -p "按任意键返回上一级菜单..."' "$SCRIPT_FILE"
grep -Fq 'test_choice_action' "$SCRIPT_FILE"
! grep -Fq 'run_test_script_action "ChatGPT 解锁状态检测" bash -c' "$SCRIPT_FILE"
grep -Fq 'echo "0. 返回上一级菜单"' "$SCRIPT_FILE"
! grep -Fq 'echo "0. 返回主菜单"' "$SCRIPT_FILE"
grep -Fq 'echo "1. ChatGPT 解锁状态检测"' "$SCRIPT_FILE"
grep -Fq 'echo "18. NetQuality 网络质量体检脚本"' "$SCRIPT_FILE"
grep -Fq 'echo "33. nodequality 融合怪测评"' "$SCRIPT_FILE"
! grep -Fq '1) refresh_screen; toggle_tg_monitor; finish_menu_action ;;' "$SCRIPT_FILE"
! grep -Fq '2) refresh_screen; toggle_tg_login_notify; finish_menu_action ;;' "$SCRIPT_FILE"
! grep -Fq 'local ssh_file=' "$SCRIPT_FILE"
! grep -Fq 'local ssh_url=' "$SCRIPT_FILE"
! grep -Fq 'local notify_file="$HOME/TG-notify.sh"' "$SCRIPT_FILE"
